FROM apache/airflow:2.10.2
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
         nano \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}"

# CMD airflow db init && \
#     airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && \
#     sleep 30 && \
#     airflow webserver --port 8080 & && \
#     sleep 30 && \
#     airflow scheduler
ENV AIRFLOW__CORE__TEST_CONNECTION=Enabled
USER root

EXPOSE 8080

# docker run -it -p 8081:8080 -v C:/Users/siddh/OneDrive/Documents/Airflow/dags:/opt/airflow/dags airflow:26 bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && sleep 30 && airflow webserver --port 8080 & sleep 30 && airflow scheduler"